/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;

/**
 *
 * @author Bryan
 */
public class viewUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewUsuario
     */
    public viewUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAgregarUsuario = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        BtnModificarUsuario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnEliminarUsuario = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnImprimirUsuario = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        txtbuscar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jBtnBuscarCliente = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setClosable(true);

        jLabel4.setBackground(new java.awt.Color(250, 112, 112));
        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(61, 131, 97));
        jLabel4.setText("VISTA DE USUARIOS");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setBorderPainted(false);
        jToolBar1.add(jSeparator1);

        btnAgregarUsuario.setBackground(new java.awt.Color(210, 215, 159));
        btnAgregarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarUsuario.setText("AGREGAR");
        btnAgregarUsuario.setBorder(null);
        btnAgregarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregarUsuario);
        jToolBar1.add(jSeparator5);

        BtnModificarUsuario.setBackground(new java.awt.Color(210, 215, 159));
        BtnModificarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnModificarUsuario.setText("MODIFICAR");
        BtnModificarUsuario.setBorder(null);
        BtnModificarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnModificarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BtnModificarUsuario);
        jToolBar1.add(jSeparator2);

        btnEliminarUsuario.setBackground(new java.awt.Color(210, 215, 159));
        btnEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarUsuario.setText("ELIMINAR");
        btnEliminarUsuario.setBorder(null);
        btnEliminarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEliminarUsuario);
        jToolBar1.add(jSeparator3);

        jBtnImprimirUsuario.setBackground(new java.awt.Color(210, 215, 159));
        jBtnImprimirUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnImprimirUsuario.setText("IMPRIMIR REPORTE");
        jBtnImprimirUsuario.setBorder(null);
        jBtnImprimirUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnImprimirUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnImprimirUsuario);
        jToolBar1.add(jSeparator4);

        txtbuscar.setBackground(new java.awt.Color(177, 215, 180));
        txtbuscar.setFont(new java.awt.Font("MS PGothic", 0, 24)); // NOI18N
        txtbuscar.setToolTipText("PUEDE BUSCAR MEDIANTE CEDULA, NOMBRE, APELLIDO O USUARIO");
        txtbuscar.setBorder(null);
        txtbuscar.setPreferredSize(new java.awt.Dimension(50, 22));
        jToolBar1.add(txtbuscar);
        jToolBar1.add(jSeparator6);

        jBtnBuscarCliente.setBackground(new java.awt.Color(210, 215, 159));
        jBtnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnBuscarCliente.setText("BUSCAR");
        jBtnBuscarCliente.setBorder(null);
        jBtnBuscarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnBuscarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnBuscarCliente);
        jToolBar1.add(jSeparator8);

        tblUsuarios.setBackground(new java.awt.Color(255, 253, 227));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "", "Foto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 70, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 382, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificarUsuario;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton jBtnBuscarCliente;
    private javax.swing.JButton jBtnImprimirUsuario;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnModificarUsuario() {
        return BtnModificarUsuario;
    }

    public void setBtnModificarUsuario(JButton BtnModificarUsuario) {
        this.BtnModificarUsuario = BtnModificarUsuario;
    }

    public JButton getBtnAgregarUsuario() {
        return btnAgregarUsuario;
    }

    public void setBtnAgregarUsuario(JButton btnAgregarUsuario) {
        this.btnAgregarUsuario = btnAgregarUsuario;
    }

    public JButton getBtnEliminarUsuario() {
        return btnEliminarUsuario;
    }

    public void setBtnEliminarUsuario(JButton btnEliminarUsuario) {
        this.btnEliminarUsuario = btnEliminarUsuario;
    }

    public JButton getjBtnBuscarCliente() {
        return jBtnBuscarCliente;
    }

    public void setjBtnBuscarCliente(JButton jBtnBuscarCliente) {
        this.jBtnBuscarCliente = jBtnBuscarCliente;
    }

    public JButton getjBtnImprimirUsuario() {
        return jBtnImprimirUsuario;
    }

    public void setjBtnImprimirUsuario(JButton jBtnImprimirUsuario) {
        this.jBtnImprimirUsuario = jBtnImprimirUsuario;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JToolBar.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JToolBar.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JToolBar.Separator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JToolBar.Separator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JToolBar.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JToolBar.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }

    public JToolBar.Separator getjSeparator4() {
        return jSeparator4;
    }

    public void setjSeparator4(JToolBar.Separator jSeparator4) {
        this.jSeparator4 = jSeparator4;
    }

    public JToolBar.Separator getjSeparator5() {
        return jSeparator5;
    }

    public void setjSeparator5(JToolBar.Separator jSeparator5) {
        this.jSeparator5 = jSeparator5;
    }

    public JToolBar.Separator getjSeparator6() {
        return jSeparator6;
    }

    public void setjSeparator6(JToolBar.Separator jSeparator6) {
        this.jSeparator6 = jSeparator6;
    }

    public JToolBar.Separator getjSeparator8() {
        return jSeparator8;
    }

    public void setjSeparator8(JToolBar.Separator jSeparator8) {
        this.jSeparator8 = jSeparator8;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JTable getTblUsuarios() {
        return tblUsuarios;
    }

    public void setTblUsuarios(JTable tblUsuarios) {
        this.tblUsuarios = tblUsuarios;
    }

    public JTextField getTxtbuscar() {
        return txtbuscar;
    }

    public void setTxtbuscar(JTextField txtbuscar) {
        this.txtbuscar = txtbuscar;
    }





}
